services:
  nest:
    container_name: restapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:hendra@localhost:5432/NineThrift?schema=public

  postgres:
    container_name: db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hendra
      - POSTGRES_DB=NineThrift 